- type: antag
  id: SSF
  name: roles-antag-ssf-name
  antagonist: true
  setPreference: false
  objective: roles-antag-ssf-objective
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 2h
  playTimeTracker: AntagSSF
