- type: antag
  id: Vampire
  name: roles-antag-vampire-name
  antagonist: true
  setPreference: true
  objective: roles-antag-vampire-description
  requirements:
  - !type:SpeciesRequirement
    species:
    - IPC
    inverted: true
  playTimeTracker: AntagVampire

- type: antagSpecifier
  parent: VampireRestrictedAntag
  id: Vampire
  prefRoles:
  - Vampire
  allowNonHumans: true
  tags:
    - CantBecomeRevolutionary
  blacklist:
    components:
    - AntagImmune
  mindRoles:
  - MindRoleVampire

- type: antag
  id: Thrall
  name: roles-antag-thrall-name
  antagonist: true
  setPreference: false
  objective: roles-antag-thrall-objective
