- type: job
  id: BlueShield
  name: job-name-blueshield
  jobSelectName: job-name-blueshield-job-select
  description: job-description-blueshield
  playTimeTracker: JobBlueShield
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 10h
  - !type:DepartmentTimeRequirement
    department: Representatives
    time: 5h
  - !type:RoleTimeRequirement
    role: JobBrigmedic
    time: 3h
  - !type:RolesRequirement
    proto: CCEReq
  - !type:TraitsRequirement
    traits:
      - Iterator
    inverted: true
  startingGear: CentralCommandEnforcerGear
  icon: JobIconBlueShield
  rules: job-rules-corporate-aligned
  supervisors: job-supervisors-centcom
  displayWeight: 40
  access:
    - Command
    - Bar
    - Service
    - Maintenance
    - Janitor
    - Theatre
    - Kitchen
    - Chapel
    - Hydroponics
    - External
    - Chemistry
    - Engineering
    - Research
    - Robotics
    - Detective
    - Salvage
    - Security
    - Brigmedic
    - Brig
    - Lawyer
    - Cargo
    - Mail
    - Atmospherics
    - Medical
    - IAA
    - BlueShield
    - Surgery
    - Paramedic
    - Mining
    - SalvageLead
    - Debrief
  special:
    - !type:AddImplantSpecial
      implants: [MindShieldImplant]

- type: startingGear
  id: CentralCommandEnforcerGear
  equipment:
    # head: ClothingHeadHatBeretBlueShield
    # id: BlueShieldPDA
    ears: ClothingHeadsetAltCCRep
    # belt: ClothingBeltBlueShieldWebbingFilled
    pocket1: WeaponPistolBlueguard
    pocket2: HandheldBSOCrewMonitor
  storage:
    back:
    - Flash
    - ClothingMaskGasCCE

- type: chameleonOutfit
  id: BlueShieldChameleonOutfit
  job: BlueShield
  equipment:
    head: ClothingHeadHatBeretBlueShield
    gloves: ClothingHandsGlovesCombat
